# Generated by Django 5.2.6 on 2025-09-09 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Xolat',
                'verbose_name_plural': 'Xolatlar',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Shaxar',
                'verbose_name_plural': 'Shaxarlar',
            },
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': "To'lo'v",
                'verbose_name_plural': "To'lo'vlar",
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzili')),
                ('title', models.CharField(max_length=250, verbose_name='Maqola nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Maqola matni')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('item', models.CharField(max_length=155, verbose_name='Maxsulot nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasmi')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Videosi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('published', models.BooleanField(default=True, verbose_name='Saytga chiqarish')),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name="Bo'limi")),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condition', verbose_name='Maxsulot xolati')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location', verbose_name='Shaxar')),
                ('pay_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.paytype', verbose_name="To'lo'v turi")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqti')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ads', verbose_name='Maqola')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Avtor')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created'],
            },
        ),
    ]
